import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Key starter deck cards that are commonly referenced
const STARTER_DECK_CARDS = [
  // ST-01: Straw Hat Crew
  {
    apiId: 'ST01-001',
    cardNumber: '001',
    name: 'Monkey.D.Luffy',
    setCode: 'ST-01',
    setName: 'Straw Hat Crew',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Red',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST01-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST01-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST01-001.jpg',
    isActive: true,
  },
  {
    apiId: 'ST01-002',
    cardNumber: '002',
    name: 'Roronoa Zoro',
    setCode: 'ST-01',
    setName: 'Straw Hat Crew',
    rarity: 'Common',
    cardType: 'Character',
    cost: 2,
    power: 2000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Red',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST01-002.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST01-002.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST01-002.jpg',
    isActive: true,
  },
  {
    apiId: 'ST01-003',
    cardNumber: '003',
    name: 'Nami',
    setCode: 'ST-01',
    setName: 'Straw Hat Crew',
    rarity: 'Common',
    cardType: 'Character',
    cost: 1,
    power: 1000,
    counterPower: 1000,
    attribute: 'Intellect',
    color: 'Red',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST01-003.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST01-003.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST01-003.jpg',
    isActive: true,
  },

  // ST-02: Worst Generation
  {
    apiId: 'ST02-001',
    cardNumber: '001',
    name: 'Eustass "Captain" Kid',
    setCode: 'ST-02',
    setName: 'Worst Generation',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Red',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST02-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST02-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST02-001.jpg',
    isActive: true,
  },

  // ST-03: The Seven Warlords of the Sea
  {
    apiId: 'ST03-001',
    cardNumber: '001',
    name: 'Crocodile',
    setCode: 'ST-03',
    setName: 'The Seven Warlords of the Sea',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Blue',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST03-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST03-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST03-001.jpg',
    isActive: true,
  },

  // ST-04: Animal Kingdom Pirates
  {
    apiId: 'ST04-001',
    cardNumber: '001',
    name: 'Kaido',
    setCode: 'ST-04',
    setName: 'Animal Kingdom Pirates',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Purple',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST04-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST04-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST04-001.jpg',
    isActive: true,
  },

  // ST-05: One Piece Film Edition
  {
    apiId: 'ST05-001',
    cardNumber: '001',
    name: 'Shanks',
    setCode: 'ST-05',
    setName: 'One Piece Film Edition',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Red',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST05-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST05-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST05-001.jpg',
    isActive: true,
  },

  // ST-06: Absolute Justice
  {
    apiId: 'ST06-001',
    cardNumber: '001',
    name: 'Sakazuki',
    setCode: 'ST-06',
    setName: 'Absolute Justice',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Black',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST06-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST06-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST06-001.jpg',
    isActive: true,
  },

  // ST-07: Big Mom Pirates
  {
    apiId: 'ST07-001',
    cardNumber: '001',
    name: 'Charlotte Linlin',
    setCode: 'ST-07',
    setName: 'Big Mom Pirates',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Yellow',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST07-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST07-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST07-001.jpg',
    isActive: true,
  },

  // ST-08: Monkey D. Luffy
  {
    apiId: 'ST08-001',
    cardNumber: '001',
    name: 'Monkey.D.Luffy',
    setCode: 'ST-08',
    setName: 'Monkey D. Luffy',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Red',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST08-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST08-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST08-001.jpg',
    isActive: true,
  },

  // ST-09: Yamato
  {
    apiId: 'ST09-001',
    cardNumber: '001',
    name: 'Yamato',
    setCode: 'ST-09',
    setName: 'Yamato',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Green',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST09-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST09-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST09-001.jpg',
    isActive: true,
  },

  // ST-10: The Three Captains
  {
    apiId: 'ST10-001',
    cardNumber: '001',
    name: 'Monkey.D.Luffy',
    setCode: 'ST-10',
    setName: 'The Three Captains',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Red',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST10-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST10-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST10-001.jpg',
    isActive: true,
  },

  // ST-22: Ace & Newgate (the one from your import example)
  {
    apiId: 'ST22-001',
    cardNumber: '001',
    name: 'Portgas D. Ace & Edward Newgate',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Leader',
    cardType: 'Leader',
    cost: null,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Blue',
    effectText: 'This Leader can attack the opponent\'s Leader even if there are Characters in play.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-001.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-001.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-001.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-002',
    cardNumber: '002',
    name: 'Izo',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 2,
    power: 2000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-002.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-002.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-002.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-003',
    cardNumber: '003',
    name: 'Whitey Bay',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 2,
    power: 2000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-003.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-003.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-003.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-004',
    cardNumber: '004',
    name: 'Squard',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 2,
    power: 2000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-004.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-004.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-004.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-005',
    cardNumber: '005',
    name: 'Kingdew',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 2,
    power: 2000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-005.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-005.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-005.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-006',
    cardNumber: '006',
    name: 'Atmos',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 2,
    power: 2000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-006.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-006.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-006.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-007',
    cardNumber: '007',
    name: 'Marco',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 3,
    power: 3000,
    counterPower: 1000,
    attribute: 'Slash',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-007.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-007.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-007.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-008',
    cardNumber: '008',
    name: 'Portgas D. Ace',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 3,
    power: 3000,
    counterPower: 1000,
    attribute: 'Strike',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-008.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-008.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-008.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-009',
    cardNumber: '009',
    name: 'Portgas D. Ace (alt)',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 3,
    power: 3000,
    counterPower: 1000,
    attribute: 'Strike',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-009.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-009.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-009.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-010',
    cardNumber: '010',
    name: 'Jozu',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 3,
    power: 3000,
    counterPower: 1000,
    attribute: 'Strike',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-010.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-010.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-010.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-011',
    cardNumber: '011',
    name: 'Jozu (alt)',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Character',
    cost: 3,
    power: 3000,
    counterPower: 1000,
    attribute: 'Strike',
    color: 'Blue',
    effectText: null,
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-011.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-011.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-011.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-012',
    cardNumber: '012',
    name: 'Take That Back!! Take Back What You Said!!',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Event',
    cost: 2,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Blue',
    effectText: 'Draw 2 cards.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-012.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-012.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-012.jpg',
    isActive: true,
  },
  {
    apiId: 'ST22-013',
    cardNumber: '013',
    name: 'I Am Whitebeard!!',
    setCode: 'ST-22',
    setName: 'Ace & Newgate',
    rarity: 'Common',
    cardType: 'Event',
    cost: 2,
    power: null,
    counterPower: null,
    attribute: null,
    color: 'Blue',
    effectText: 'Your Leader gains +1000 power this turn.',
    flavorText: null,
    imageUrl: 'https://images.optcgapi.com/cards/ST22-013.jpg',
    smallImageUrl: 'https://images.optcgapi.com/cards/ST22-013.jpg',
    largeImageUrl: 'https://images.optcgapi.com/cards/ST22-013.jpg',
    isActive: true,
  },
];

async function main() {
  console.log('🌱 Starting One Piece TCG starter deck cards seeding...');
  console.log(`📚 Adding ${STARTER_DECK_CARDS.length} key starter deck cards`);

  let successCount = 0;
  let errorCount = 0;

  for (const cardData of STARTER_DECK_CARDS) {
    try {
      await prisma.card.upsert({
        where: { apiId: cardData.apiId },
        update: cardData,
        create: cardData,
      });
      console.log(`✅ Seeded starter deck card: ${cardData.name} (${cardData.rarity}) from ${cardData.setCode}`);
      successCount++;
    } catch (error: any) {
      console.error(`❌ Error seeding starter deck card ${cardData.name} from ${cardData.setCode}:`, error.message);
      errorCount++;
    }
  }

  console.log(`\n🎉 Starter deck seeding completed!`);
  console.log(`✅ Successfully seeded: ${successCount} cards`);
  console.log(`❌ Total errors: ${errorCount} cards`);
}

main()
  .catch((e) => {
    console.error('💥 Fatal error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
