import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../common/prisma/prisma.service';

@Injectable()
export class DecksService {
  constructor(private prisma: PrismaService) {}

  async findAll(userId: string) {
    return this.prisma.deck.findMany({
      where: { userId },
      include: {
        cards: {
          include: {
            card: true,
          },
        },
        leader: true,
      },
    });
  }

  async create(userId: string, data: any) {
    const { cards, leaderId, ...deckData } = data;
    
    // Consolidate duplicate cards by summing their quantities
    const consolidatedCards = cards.reduce((acc: any, cardData: any) => {
      const existingCard = acc.find((c: any) => c.cardId === cardData.cardId);
      if (existingCard) {
        existingCard.quantity += cardData.quantity;
      } else {
        acc.push({
          cardId: cardData.cardId,
          quantity: cardData.quantity,
        });
      }
      return acc;
    }, []);
    
    return this.prisma.deck.create({
      data: {
        ...deckData,
        userId,
        leaderId,
        cards: {
          create: consolidatedCards,
        },
      },
      include: {
        cards: {
          include: {
            card: true,
          },
        },
        leader: true,
      },
    });
  }

  async findOne(id: string, userId: string) {
    return this.prisma.deck.findFirst({
      where: { id, userId },
      include: {
        cards: {
          include: {
            card: true,
          },
        },
        leader: true,
      },
    });
  }

  async update(id: string, userId: string, data: any) {
    const { cards, leaderId, ...deckData } = data;
    
    // Update deck info
    const deck = await this.prisma.deck.update({
      where: { id, userId },
      data: {
        ...deckData,
        leaderId,
      },
    });

    // Update cards if provided
    if (cards) {
      // Consolidate duplicate cards by summing their quantities
      const consolidatedCards = cards.reduce((acc: any, cardData: any) => {
        const existingCard = acc.find((c: any) => c.cardId === cardData.cardId);
        if (existingCard) {
          existingCard.quantity += cardData.quantity;
        } else {
          acc.push({
            cardId: cardData.cardId,
            quantity: cardData.quantity,
          });
        }
        return acc;
      }, []);

      // Remove existing cards
      await this.prisma.deckCard.deleteMany({
        where: { deckId: id },
      });

      // Add new cards
      await this.prisma.deckCard.createMany({
        data: consolidatedCards.map((cardData: any) => ({
          deckId: id,
          cardId: cardData.cardId,
          quantity: cardData.quantity,
        })),
      });
    }

    return this.findOne(id, userId);
  }

  async delete(id: string, userId: string) {
    return this.prisma.deck.delete({
      where: { id, userId },
    });
  }

  async exportDeck(id: string, userId: string) {
    const deck = await this.prisma.deck.findFirst({
      where: { id, userId },
      include: {
        cards: {
          include: {
            card: true,
          },
        },
        leader: true,
      },
    });

    if (!deck) {
      throw new Error('Deck not found');
    }

    // Generate deck list in Pokémon TCG Live format
    let deckList = `****** One Piece TCG Deck List ******\n\n`;
    deckList += `Deck Name: ${deck.name}\n`;
    deckList += `Description: ${deck.description || 'No description'}\n\n`;

    // Leader section
    if (deck.leader) {
      deckList += `##Leader - 1\n\n`;
      deckList += `* 1 ${deck.leader.name} ${deck.leader.setCode} ${deck.leader.cardNumber || 'N/A'}\n\n`;
    }

    // Group cards by type
    const cardsByType = deck.cards.reduce((acc, deckCard) => {
      const cardType = deckCard.card.cardType;
      if (!acc[cardType]) {
        acc[cardType] = [];
      }
      acc[cardType].push(deckCard);
      return acc;
    }, {} as Record<string, any[]>);

    // Add each card type section
    Object.entries(cardsByType).forEach(([cardType, cards]) => {
      deckList += `##${cardType}s - ${cards.reduce((sum, dc) => sum + dc.quantity, 0)}\n\n`;
      cards.forEach(deckCard => {
        deckList += `* ${deckCard.quantity} ${deckCard.card.name} ${deckCard.card.setCode} ${deckCard.card.cardNumber || 'N/A'}\n`;
      });
      deckList += `\n`;
    });

    // Total cards
    const totalCards = deck.cards.reduce((sum, dc) => sum + dc.quantity, 0) + (deck.leader ? 1 : 0);
    deckList += `Total Cards - ${totalCards}\n\n`;
    deckList += `****** Deck List Generated by One Piece TCG ******`;

    return {
      deckList,
      deckName: deck.name,
      totalCards,
    };
  }

  async parseDeckList(deckListText: string) {
    try {
      const lines = deckListText.split('\n').map(line => line.trim()).filter(line => line);
      
      let deckName = 'Imported Deck';
      let deckDescription = '';
      let leaderCard = null;
      const cards = [];
      
      let currentSection = '';
      let cardLines = [];
      
      // Parse deck list
      for (const line of lines) {
        if (line.startsWith('Deck Name:')) {
          deckName = line.replace('Deck Name:', '').trim();
        } else if (line.startsWith('Description:')) {
          deckDescription = line.replace('Description:', '').trim();
        } else if (line.startsWith('##Leader')) {
          currentSection = 'leader';
        } else if (line.startsWith('##Characters') || line.startsWith('##Events') || line.startsWith('##Stages')) {
          currentSection = 'cards';
        } else if (line.startsWith('*') && currentSection) {
          cardLines.push(line);
        }
      }
      
      // Process card lines
      for (const line of cardLines) {
        const match = line.match(/\*\s*(\d+)\s+(.+?)\s+([A-Z]+-\d+)\s+(\d+)/);
        if (match) {
          const [, quantity, cardName, setCode, cardNumber] = match;
          const isLeader = currentSection === 'leader';
          
          if (isLeader) {
            leaderCard = {
              name: cardName,
              setCode,
              cardNumber,
            };
          } else {
            cards.push({
              name: cardName,
              setCode,
              cardNumber,
              quantity: parseInt(quantity),
            });
          }
        }
      }

      // Find cards in database
      const foundCards = [];
      const notFoundCards = [];

      // Find leader
      if (leaderCard) {
        // Try exact match first
        let leader = await this.prisma.card.findFirst({
          where: {
            name: leaderCard.name,
            setCode: leaderCard.setCode,
            cardType: 'Leader',
          },
        });
        
        // If no exact match, try partial name match
        if (!leader) {
          leader = await this.prisma.card.findFirst({
            where: {
              name: {
                contains: leaderCard.name.split(' ')[0], // Try first word
                mode: 'insensitive',
              },
              setCode: leaderCard.setCode,
              cardType: 'Leader',
            },
          });
        }
        
        if (leader) {
          foundCards.push({ card: leader, quantity: 1, isLeader: true });
        } else {
          notFoundCards.push({ ...leaderCard, quantity: 1, isLeader: true });
        }
      }

      // Find other cards
      for (const cardData of cards) {
        // Try exact match first
        let card = await this.prisma.card.findFirst({
          where: {
            name: cardData.name,
            setCode: cardData.setCode,
          },
        });
        
        // If no exact match, try partial name match
        if (!card) {
          card = await this.prisma.card.findFirst({
            where: {
              name: {
                contains: cardData.name.split(' ')[0], // Try first word
                mode: 'insensitive',
              },
              setCode: cardData.setCode,
            },
          });
        }
        
        if (card) {
          foundCards.push({ card, quantity: cardData.quantity, isLeader: false });
        } else {
          notFoundCards.push(cardData);
        }
      }

      // Return parsed data without creating a deck
      return {
        deckName,
        deckDescription,
        leader: foundCards.find(fc => fc.isLeader)?.card || null,
        cards: foundCards.filter(fc => !fc.isLeader).map(fc => ({
          card: fc.card,
          quantity: fc.quantity,
        })),
        foundCards: foundCards.length,
        notFoundCards: notFoundCards.length,
        notFoundCardsList: notFoundCards,
        debugInfo: {
          parsedCards: cards.length,
          parsedLeader: leaderCard ? leaderCard.name : 'None',
          cardLines: cardLines.length,
        },
        message: `Deck parsed successfully! Found ${foundCards.length} cards, ${notFoundCards.length} cards not found.`,
      };
    } catch (error) {
      throw new Error(`Failed to parse deck list: ${error.message}`);
    }
  }

  async importDeck(deckListText: string, userId: string, customName?: string) {
    try {
      // Parse the deck list text
      const lines = deckListText.split('\n').map(line => line.trim()).filter(line => line);
      
      let deckName = customName || 'Imported Deck';
      let leaderCard = null;
      const cards: Array<{ name: string; setCode: string; cardNumber: string; quantity: number }> = [];

      // Find deck name
      const nameLine = lines.find(line => line.startsWith('Deck Name:'));
      if (nameLine) {
        deckName = nameLine.replace('Deck Name:', '').trim();
      }

      // Parse card lines (lines that start with * or just numbers)
      const cardLines = lines.filter(line => 
        line.startsWith('*') || 
        /^\d+\s+/.test(line) // Lines that start with a number followed by space
      );
      
      for (const line of cardLines) {
        let match;
        
        // Try format with asterisk first: * quantity Card Name SetCode CardNumber
        match = line.match(/\*\s+(\d+)\s+(.+?)\s+([A-Z0-9-]+)\s+([A-Z0-9-]+)$/);
        
        // If no match, try format without asterisk: quantity Card Name SetCode CardNumber
        if (!match) {
          match = line.match(/^(\d+)\s+(.+?)\s+([A-Z0-9-]+)\s+([A-Z0-9-]+)$/);
        }
        
        if (match) {
          const [, quantity, cardName, setCode, cardNumber] = match;
          
          // Check if it's a leader (from Leader section or contains leader keywords)
          const isLeader = line.includes('Leader') || 
                          cardName.toLowerCase().includes('leader') ||
                          cardName.includes('&') || // Many leaders have "&" in their names
                          cardName.includes('Ace') && cardName.includes('Whitebeard'); // Specific case
          
          if (isLeader) {
            leaderCard = {
              name: cardName,
              setCode,
              cardNumber,
            };
          } else {
            cards.push({
              name: cardName,
              setCode,
              cardNumber,
              quantity: parseInt(quantity),
            });
          }
        }
      }

      // Find cards in database
      const foundCards = [];
      const notFoundCards = [];

      // Find leader
      if (leaderCard) {
        // Try exact match first
        let leader = await this.prisma.card.findFirst({
          where: {
            name: leaderCard.name,
            setCode: leaderCard.setCode,
            cardType: 'Leader',
          },
        });
        
        // If no exact match, try partial name match
        if (!leader) {
          leader = await this.prisma.card.findFirst({
            where: {
              name: {
                contains: leaderCard.name.split(' ')[0], // Try first word
                mode: 'insensitive',
              },
              setCode: leaderCard.setCode,
              cardType: 'Leader',
            },
          });
        }
        
        if (leader) {
          foundCards.push({ card: leader, quantity: 1, isLeader: true });
        } else {
          notFoundCards.push({ ...leaderCard, quantity: 1, isLeader: true });
        }
      }

      // Find other cards
      for (const cardData of cards) {
        // Try exact match first
        let card = await this.prisma.card.findFirst({
          where: {
            name: cardData.name,
            setCode: cardData.setCode,
          },
        });
        
        // If no exact match, try partial name match
        if (!card) {
          card = await this.prisma.card.findFirst({
            where: {
              name: {
                contains: cardData.name.split(' ')[0], // Try first word
                mode: 'insensitive',
              },
              setCode: cardData.setCode,
            },
          });
        }
        
        if (card) {
          foundCards.push({ card, quantity: cardData.quantity, isLeader: false });
        } else {
          notFoundCards.push(cardData);
        }
      }

      // Create the deck
      const deck = await this.prisma.deck.create({
        data: {
          name: deckName,
          description: `Imported deck from deck list`,
          userId,
          isPublic: false,
          leaderId: foundCards.find(fc => fc.isLeader)?.card?.id,
        },
      });

      // Add found cards to deck
      for (const foundCard of foundCards.filter(fc => !fc.isLeader)) {
        await this.prisma.deckCard.create({
          data: {
            deckId: deck.id,
            cardId: foundCard.card.id,
            quantity: foundCard.quantity,
          },
        });
      }

      // Fetch the complete deck with leader relation
      const completeDeck = await this.prisma.deck.findUnique({
        where: { id: deck.id },
        include: {
          cards: {
            include: {
              card: true,
            },
          },
          leader: true,
        },
      });

      return {
        deck: completeDeck,
        foundCards: foundCards.length,
        notFoundCards: notFoundCards.length,
        notFoundCardsList: notFoundCards,
        debugInfo: {
          parsedCards: cards.length,
          parsedLeader: leaderCard ? leaderCard.name : 'None',
          cardLines: cardLines.length,
        },
        message: `Deck imported successfully! Found ${foundCards.length} cards, ${notFoundCards.length} cards not found.`,
      };
    } catch (error) {
      throw new Error(`Failed to import deck: ${error.message}`);
    }
  }
}
